apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-processor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: image-processor
  template:
    metadata:
      labels:
        app: image-processor
    spec:
      containers:
      - name: image-processor
        image: 769566606308.dkr.ecr.us-east-1.amazonaws.com/image-processor:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: image-processor-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: image-processor
